version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-task-flow
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: todo-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-task-flow:5432/task-management # використовуємо порт 5432 всередині контейнера
    command: ['yarn', 'start']
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
