export default {
  BAD_REQUEST: 'BAD_REQUEST',

  CONFLICT: 'CONFLICT',

  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_NOT_SENT: 'EMAIL_NOT_SENT',
  EMAIL_SENDING_FAILED: 'EMAIL_SENDING_FAILED',
  EMAIL_THE_SAME_AS_CURRENT: 'EMAIL_THE_SAME_AS_CURRENT',

  FORBIDDEN: 'FORBIDDEN',

  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_TOKEN: 'INVALID_TOKEN',

  NO_ACCESS_TOKEN_PROVIDED: 'NO_ACCESS_TOKEN_PROVIDED',
  NOT_FOUND: 'NOT_FOUND',

  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  PASSWORD_RESET_TOKEN_NOT_FOUND: 'PASSWORD_RESET_TOKEN_NOT_FOUND',
  PASSWORD_THE_SAME_AS_CURRENT: 'PASSWORD_THE_SAME_AS_CURRENT',

  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;
