export default {
  USER_AUTHENTICATED: 'USER_SUCCESSFULLY_AUTHENTICATED',
  EMAIL_SENT_SUCCESSFULLY: 'EMAIL_SENT_SUCCESSFULLY',
  PASSWORD_RESET_SUCCESSFULLY: 'PASSWORD_RESET_SUCCESSFULLY',
} as const;
